apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontendpages.frontend.thegostev.com
spec:
  group: frontend.thegostev.com
  names:
    kind: FrontendPage
    listKind: FrontendPageList
    plural: frontendpages
    singular: frontendpage
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - title
                - template
                - components
              properties:
                title:
                  type: string
                template:
                  type: string
                components:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - type
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                      config:
                        type: object
                        additionalProperties: true
                theme:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
                url:
                  type: string
                componentCount:
                  type: integer
                lastUpdated:
                  type: string
                  format: date-time
      subresources:
        status: {}
