name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24.4'

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ hashFiles('**/go.sum') }}-v2
        restore-keys: |
          go-mod-

    - name: Install dependencies
      run: make install

    - name: Dependency Check (go mod tidy)
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
          echo "Dependencies are not tidy. Please run 'go mod tidy' and commit changes."
          git --no-pager diff go.mod go.sum
          exit 1
        fi

    - name: Run code formatting check
      run: |
        make fmt
        if [ -n "$(git status --porcelain)" ]; then
          echo "Code is not formatted. Please run 'make fmt' and commit the changes."
          git --no-pager diff
          exit 1
        fi

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest

    - name: Run linting
      run: make lint

    - name: Run tests
      run: make test

    - name: Build binary
      run: make build

    - name: Test Docker build (without push)
      run: |
        docker build -t go-kubernetes-controllers:test .
        echo "Docker build successful"

    - name: Test Helm chart
      run: |
        helm lint charts/app/
        echo "Helm chart validation successful"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: controller-binary
        path: controller

    - name: Cleanliness Check (no uncommitted changes)
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Uncommitted changes detected after build. Please investigate."
          git --no-pager diff
          exit 1
        fi 